apiVersion : apps/v1
kind: Deployment
metadata:
  name: nmishrpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmishrpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: nmishrpipelinesjavascriptdocker 
    spec:
      containers:
        - name: nmishrpipelinesjavascriptdocker 
          image: nvmcontainerreg.azurecr.io/nmishrpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
          - containerPort: 8080
---
apiVersion : apps/v1
kind: CronJob
metadata:
  name: nmishrpipelinesjavascriptdocker 
spec:
  schedule: "30 14 * * *"
  jobTemplate:
    spec:
      replicas: 6
      selector:
        matchLabels:
          app: nmishrpipelinesjavascriptdocker
      template:
        metadata:
          labels:
            app: nmishrpipelinesjavascriptdocker 
        spec:
          containers:
            - name: nmishrpipelinesjavascriptdocker 
              image: nvmcontainerreg.azurecr.io/nmishrpipelinesjavascriptdocker
              ports:
              - containerPort: 8080
---
apiVersion : apps/v1
kind: CronJob
metadata:
  name: nmishrpipelinesjavascriptdocker 
spec:
  schedule: "45 14 * * *"
  jobTemplate:
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nmishrpipelinesjavascriptdocker
      template:
        metadata:
          labels:
            app: nmishrpipelinesjavascriptdocker 
        spec:
          containers:
            - name: nmishrpipelinesjavascriptdocker 
              image: nvmcontainerreg.azurecr.io/nmishrpipelinesjavascriptdocker
              ports:
              - containerPort: 8080

